"""add_setup_wizard_fields

Revision ID: 2aed138eb160
Revises: 9e8f7a6b3c4a
Create Date: 2025-10-26 03:43:46.460637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2aed138eb160'
down_revision = '9e8f7a6b3c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user', sa.Column('faqs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'faqs')
    op.drop_column('user', 'profile_type')
    # ### end Alembic commands ###
