"""Add foreign key constraint to link user.id to auth.users.id

Revision ID: b2dddd882db1
Revises: feff4ca7d503
Create Date: 2025-07-19 17:43:51.582831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dddd882db1'
down_revision = 'feff4ca7d503'
branch_labels = None
depends_on = None


def upgrade():
    # Grant usage on auth schema to current user (idempotent)
    op.execute("GRANT USAGE ON SCHEMA auth TO CURRENT_USER;")

    # Add foreign key constraint linking public.user.id to auth.users.id
    op.create_foreign_key(
        "fk_user_id_auth_users",
        source_table="user",
        referent_table="users",
        local_cols=["id"],
        remote_cols=["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint
    op.drop_constraint("fk_user_id_auth_users", "user", type_="foreignkey")
    # ### end Alembic commands ###
