"""add_knowledge_base_to_workspace

Revision ID: bbf7c4e0e730
Revises: e16184f3f2b8
Create Date: 2025-11-02 23:45:30.617925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbf7c4e0e730'
down_revision = 'e16184f3f2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('knowledge_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'knowledge_base')
    # ### end Alembic commands ###
